import {SEARCH_MOVIE,FETCH_MOVIES,FETCH_MOVIE,LOADING} from "./types";
import axios from 'axios';
import {APIKey} from '../APIKey';
export const searchMovie = text=>dispatch=>{
dispatch({
    type: SEARCH_MOVIE,
    payload:text
});
};
export const fetchMovies = text=>dispatch=>{
    axios
    .get(`https://www.omdbapi.com/?apikey=${APIKey}&s=${text}`)
    .then(response =>
        dispatch({
        type:FETCH_MOVIES,
        payload:response.data//because there are 2 things recived from api first is the search array containing all the data of movies and other is the response which is boolean
    })
    )
    .catch((err)=>console.log(err));
};
export const fetchMovie= id=>dispatch=>{//this is for fetching the data of single movie from  api then this response generated by api is handeled by reducers folder//this action is called using the didmount function
    axios
    .get(`https://www.omdbapi.com/?apikey=${APIKey}&i=${id}`)
    .then(response =>
        dispatch({
        type:FETCH_MOVIE,
        payload:response.data
    })
    )
    .catch((err)=>console.log(err));
};
    export const setLoading = () => {
        return{    
        type:LOADING
        };
    };
